// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7G1gDpcIWPso2MGUBlved3ARQGR7lC3I',
    appId: '1:336258048021:web:9b5ef95b1d4df2a2bbee1c',
    messagingSenderId: '336258048021',
    projectId: 'girmantech',
    authDomain: 'girmantech.firebaseapp.com',
    storageBucket: 'girmantech.appspot.com',
    measurementId: 'G-3K212R6FCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJdEBBtRUY_a-uYhLpiP_soDman9Ec3L8',
    appId: '1:336258048021:android:922c80bf8db60ba5bbee1c',
    messagingSenderId: '336258048021',
    projectId: 'girmantech',
    storageBucket: 'girmantech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ-ADBfkVf1KSidOK4nmQjDJRP0v-99dg',
    appId: '1:336258048021:ios:e3a70deb6e7e1b86bbee1c',
    messagingSenderId: '336258048021',
    projectId: 'girmantech',
    storageBucket: 'girmantech.appspot.com',
    iosBundleId: 'com.example.girmanApp',
  );

}